name: projekx_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.4.0
  animated_text_kit: ^4.2.3
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0
  url_launcher: ^6.3.2
  flutter_animator: ^3.2.2
  lottie: ^3.3.1
  awesome_bottom_bar: ^1.2.4
  lucide_icons: ^0.257.0
  flutter_native_splash: ^2.4.6
  intl: ^0.20.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"         
  image: assets/icon.png  
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/

